# This file was generated by the Tkinter Designer
# https://github.com/ParthJadhav/Tkinter-Designer
# from tkinter import *
# Explicit imports to satisfy Flake8

from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from pathlib import Path
import dikstra
import fulkerson 
import kruskal 
import tkinter as tk
from tkinter import messagebox
from PIL import Image, ImageTk
import heapq
import networkx as nx
import matplotlib.pyplot as plt
import dikstra
import fulkerson
import kruskal
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import csv

def ejecutar_dijkstra():
    print("button_1 clicked")
    dikstra.main()

def ejecutar_fulkerson():
    print("button_2 clicked")
    fulkerson.main()

def ejecutar_kruskal():
    print("button_3 clicked")
    kruskal.main()

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / "frame0"

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("790x628")
window.configure(bg = "#F7FFDF")

canvas = Canvas(
    window,
    bg = "#F7FFDF",
    height = 628,
    width = 790,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    558.0,
    790.0,
    630.0,
    fill="#F6B364",
    outline=""
)

canvas.create_rectangle(
    0.0,
    25.0,
    1440.0,
    573.0,
    fill="#F89B2E",
    outline=""
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    168.0694580078125,
    387.2361145019531,
    image=image_image_1
)

canvas.create_text(
    40.048583984375,
    122.34027099609375,
    anchor="nw",
    text="BODEGA UNO - TU MEJOR OPCIÓN \n",
    fill="#000000",
    font=("Inter", 35 * -1)
)

canvas.create_rectangle(
    0.0,
    1.09722900390625,
    790.0,
    52.11806106567383,
    fill="#D9D9D9",
    outline=""
)

canvas.create_text(
    12.0694580078125,
    3.291656494140625,
    anchor="nw",
    text="BD ",
    fill="#A90A0A",
    font=("Inter BlackItalic", 35 * -1)
)

canvas.create_rectangle(
    77.35416674613953,
    -1.6458332538604736,
    79.0,
    49.92361068725586,
    fill="#A90A0A",
    outline=""
)

canvas.create_text(
    90.52081298828125,
    12.0694580078125,
    anchor="nw",
    text="PRODUCTOS",
    fill="#000000",
    font=("Inter BlackItalic", 19 * -1)
)

canvas.create_text(
    249.6180419921875,
    12.0694580078125,
    anchor="nw",
    text="SOLUCIONES",
    fill="#000000",
    font=("Inter BlackItalic", 19 * -1)
)

canvas.create_text(
    413.1041259765625,
    12.0694580078125,
    anchor="nw",
    text="CONTACTANOS",
    fill="#000000",
    font=("Inter BlackItalic", 19 * -1)
)

canvas.create_text(
    576.59033203125,
    12.0694580078125,
    anchor="nw",
    text="PERFIL ",
    fill="#000000",
    font=("Inter BlackItalic", 19 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    757.6875,
    23.9375,
    image=image_image_2
)

canvas.create_rectangle(
    395.0,
    217.25,
    740.0763854980469,
    494.84722900390625,
    fill="#D9D9D9",
    outline=""
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=ejecutar_kruskal,
    relief="flat"
)
button_1.place(
    x=413.1041259765625,
    y=415.2986145019531,
    width=322.3333435058594,
    height=29.16666603088379
)

canvas.create_text(
    12.0,
    573.0,
    anchor="nw",
    text="RUTAS ÓPTIMAS",
    fill="#000000",
    font=("Inter", 35 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    444.0416259765625,
    261.4861145019531,
    image=image_image_3
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=ejecutar_fulkerson,
    relief="flat"
)
button_2.place(
    x=413.1041259765625,
    y=359.34027099609375,
    width=200.3333282470703,
    height=29.16666603088379
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=ejecutar_dijkstra,
    relief="flat"
)
button_3.place(
    x=412.0,
    y=303.0,
    width=162.3333282470703,
    height=30.0
)

window.resizable(False, False)
window.mainloop()
